"""LLM-based detection: ask each model whether a response was generated by AI.

    python -m detect.zero_shot responses.jsonl --out labels.csv [--models ...]

Input is JSONL with one survey response per line: {"id", "survey", "question_id", "text"}.
Output is one row per response with a column per model: "1" (AI-generated), "0" (human), or
empty when the model's reply is not a bare 0 or 1. Decoding is greedy (temperature 0).
Rows already present in --out are skipped, so an interrupted run can be resumed.
"""
import argparse
import csv
import os

from .common import MODELS, chat, client, prompt, read_jsonl


def parse(reply):
    """Normalise a reply to "1", "0" or "" (invalid)."""
    return {"1": "1", "0": "0", "1.0": "1", "0.0": "0"}.get(reply.strip(), "")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("responses")
    ap.add_argument("--out", required=True)
    ap.add_argument("--models", nargs="+", default=MODELS)
    args = ap.parse_args()

    template = prompt("zero_shot")
    rows = read_jsonl(args.responses)
    done = set()
    if os.path.exists(args.out):
        with open(args.out, encoding="utf-8") as f:
            done = {r["id"] for r in csv.DictReader(f)}
    cli = client()
    new_file = not os.path.exists(args.out)
    with open(args.out, "a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["id", "survey", "question_id"] + args.models)
        if new_file:
            w.writeheader()
        for r in rows:
            if r["id"] in done or not r["text"].strip():
                continue
            out = {"id": r["id"], "survey": r["survey"], "question_id": r["question_id"]}
            for m in args.models:
                out[m] = parse(chat(cli, m, template.format(text=r["text"]), 0))
            w.writerow(out)
            f.flush()


if __name__ == "__main__":
    main()
